# system config
mode: 0
distribute: True
num_parallel_workers: 32

# dataset config
dataset: 'imagenet'
data_dir: ''
shuffle: True
dataset_download: False
batch_size: 256
drop_remainder: True
train_split: 'train'

# Augmentation config
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: 'bilinear'
crop_pct: 0.875

# model config
model: 'mobilenet_v2_100_224'
num_classes: 1000
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 100
ckpt_save_dir: ''
epoch_size: 300
dataset_sink_mode: True
amp_level: 'O0'

# loss config
loss: 'CE'
label_smoothing: 0.1

# lr scheduler config
scheduler: 'cosine_decay'
min_lr: 0.0
lr: 0.4
warmup_epochs: 4
decay_epochs: 296

# optimizer config
opt: 'momentum'
filter_bias_and_bn: True
momentum: 0.9
weight_decay: 0.00004
loss_scale: 1024
use_nesterov: False





