# system config
mode: 0
distribute: True
num_parallel_workers: 8

# dataset config
dataset: 'imagenet'
data_dir: '/data/imagenet'
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True

# Augmentation config
image_resize: 224
hflip: 0.5
color_jitter: 0.4
interpolation: 'bilinear'
crop_pct: 0.875
# re_prob: 0.5

# model config
model: 'shufflenet_v2_x0_5'
num_classes: 1000
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 30
save_checkpoint: True
ckpt_save_dir: './ckpt_v2_0.5'
epoch_size: 250
dataset_sink_mode: True
amp_level: 'O0'

# loss config
loss: 'CE'
label_smoothing: 0.1

# lr scheduler config
scheduler: 'cosine_decay'
min_lr: 0.0
lr: 0.35
warmup_epochs: 4
decay_epochs: 246

# optimizer config
opt: 'momentum'
filter_bias_and_bn: False
momentum: 0.9
weight_decay: 0.00004
loss_scale: 1
use_nesterov: False
