# system config
mode: 0
distribute: True
num_parallel_workers: 8

# dataset config
dataset: 'imagenet'
data_dir: ''
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True

# Augmentation config
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: 'bilinear'
crop_pct: 0.875

# model config
model: 'mobilenet_v1_075_224'
num_classes: 1001
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 80
ckpt_save_dir: './v1_075_ckpt'
epoch_size: 200
dataset_sink_mode: True
amp_level: 'O2'

# loss config
loss: 'CE'
label_smoothing: 0.1

# lr scheduler config
scheduler: 'cosine_decay'
min_lr: 0.0
lr: 0.4
warmup_epochs: 2
decay_epochs: 198

# optimizer config
opt: 'momentum'
filter_bias_and_bn: True
momentum: 0.9
weight_decay: 0.00003  # 改变
loss_scale: 1024  # 改变
use_nesterov: False
