# system config
mode: 0
distribute: True
num_parallel_workers: 16
device_target: 'Ascend'

# dataset config
dataset: 'imagenet'
data_url: '/cache/data'
data_dir: '/cache/data/imagenet'
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True


# Augmentation config
interpolation: 'bicubic'
re_prob: 0.1
drop_rate: 0.2
auto_augment: 'randaug-m9-mstd0.5'
re_value: 'random'



# model config
model: 'rexnet_x09'
num_classes: 1000
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 5
ckpt_save_dir: '/cache/output'
ckpt_save_policy: 'top_k'
val_split: 'val'
val_while_train: True
val_interval: 1
epoch_size: 410
dataset_sink_mode: True
amp_level: 'O3'

# loss config
loss: 'CE'
label_smoothing: 0.1

# lr scheduler config
scheduler: 'warmup_cosine_decay'
min_lr: 1.0e-6
lr: 0.45
warmup_epochs: 5
decay_epochs: 395

# optimizer config
opt: 'sgd'
filter_bias_and_bn: True
momentum: 0.9
weight_decay: 1.0e-5
loss_scale: 1024
use_nesterov: True
